<?php
/**
 * DogmaApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Tkhamez\Eve\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Sandbox Ingress (ESI) - tranquility
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tkhamez\Eve\API\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Tkhamez\Eve\API\ApiException;
use Tkhamez\Eve\API\Configuration;
use Tkhamez\Eve\API\FormDataProcessor;
use Tkhamez\Eve\API\HeaderSelector;
use Tkhamez\Eve\API\ObjectSerializer;

/**
 * DogmaApi Class Doc Comment
 *
 * @category Class
 * @package  Tkhamez\Eve\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DogmaApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getDogmaAttributes' => [
            'application/json',
        ],
        'getDogmaAttributesAttributeId' => [
            'application/json',
        ],
        'getDogmaDynamicItemsTypeIdItemId' => [
            'application/json',
        ],
        'getDogmaEffects' => [
            'application/json',
        ],
        'getDogmaEffectsEffectId' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getDogmaAttributes
     *
     * Get attributes
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributes'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return int[]|\Tkhamez\Eve\API\Model\Error
     */
    public function getDogmaAttributes($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributes'][0])
    {
        list($response) = $this->getDogmaAttributesWithHttpInfo($x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);
        return $response;
    }

    /**
     * Operation getDogmaAttributesWithHttpInfo
     *
     * Get attributes
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributes'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of int[]|\Tkhamez\Eve\API\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDogmaAttributesWithHttpInfo($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributes'][0])
    {
        $request = $this->getDogmaAttributesRequest($x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'int[]',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'int[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'int[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDogmaAttributesAsync
     *
     * Get attributes
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaAttributesAsync($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributes'][0])
    {
        return $this->getDogmaAttributesAsyncWithHttpInfo($x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDogmaAttributesAsyncWithHttpInfo
     *
     * Get attributes
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaAttributesAsyncWithHttpInfo($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributes'][0])
    {
        $returnType = 'int[]';
        $request = $this->getDogmaAttributesRequest($x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDogmaAttributes'
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDogmaAttributesRequest($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributes'][0])
    {

        // verify the required parameter 'x_compatibility_date' is set
        if ($x_compatibility_date === null || (is_array($x_compatibility_date) && count($x_compatibility_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_compatibility_date when calling getDogmaAttributes'
            );
        }





        $resourcePath = '/dogma/attributes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($if_none_match !== null) {
            $headerParams['If-None-Match'] = ObjectSerializer::toHeaderValue($if_none_match);
        }
        // header params
        if ($x_compatibility_date !== null) {
            $headerParams['X-Compatibility-Date'] = $x_compatibility_date->format('Y-m-d');
        }
        // header params
        if ($x_tenant !== null) {
            $headerParams['X-Tenant'] = ObjectSerializer::toHeaderValue($x_tenant);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDogmaAttributesAttributeId
     *
     * Get attribute information
     *
     * @param  int $attribute_id attribute_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributesAttributeId'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Tkhamez\Eve\API\Model\DogmaAttributesAttributeIdGet|\Tkhamez\Eve\API\Model\Error
     */
    public function getDogmaAttributesAttributeId($attribute_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributesAttributeId'][0])
    {
        list($response) = $this->getDogmaAttributesAttributeIdWithHttpInfo($attribute_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);
        return $response;
    }

    /**
     * Operation getDogmaAttributesAttributeIdWithHttpInfo
     *
     * Get attribute information
     *
     * @param  int $attribute_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributesAttributeId'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Tkhamez\Eve\API\Model\DogmaAttributesAttributeIdGet|\Tkhamez\Eve\API\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDogmaAttributesAttributeIdWithHttpInfo($attribute_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributesAttributeId'][0])
    {
        $request = $this->getDogmaAttributesAttributeIdRequest($attribute_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\DogmaAttributesAttributeIdGet',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Tkhamez\Eve\API\Model\DogmaAttributesAttributeIdGet',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\DogmaAttributesAttributeIdGet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDogmaAttributesAttributeIdAsync
     *
     * Get attribute information
     *
     * @param  int $attribute_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributesAttributeId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaAttributesAttributeIdAsync($attribute_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributesAttributeId'][0])
    {
        return $this->getDogmaAttributesAttributeIdAsyncWithHttpInfo($attribute_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDogmaAttributesAttributeIdAsyncWithHttpInfo
     *
     * Get attribute information
     *
     * @param  int $attribute_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributesAttributeId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaAttributesAttributeIdAsyncWithHttpInfo($attribute_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributesAttributeId'][0])
    {
        $returnType = '\Tkhamez\Eve\API\Model\DogmaAttributesAttributeIdGet';
        $request = $this->getDogmaAttributesAttributeIdRequest($attribute_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDogmaAttributesAttributeId'
     *
     * @param  int $attribute_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaAttributesAttributeId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDogmaAttributesAttributeIdRequest($attribute_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaAttributesAttributeId'][0])
    {

        // verify the required parameter 'attribute_id' is set
        if ($attribute_id === null || (is_array($attribute_id) && count($attribute_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $attribute_id when calling getDogmaAttributesAttributeId'
            );
        }

        // verify the required parameter 'x_compatibility_date' is set
        if ($x_compatibility_date === null || (is_array($x_compatibility_date) && count($x_compatibility_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_compatibility_date when calling getDogmaAttributesAttributeId'
            );
        }





        $resourcePath = '/dogma/attributes/{attribute_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($if_none_match !== null) {
            $headerParams['If-None-Match'] = ObjectSerializer::toHeaderValue($if_none_match);
        }
        // header params
        if ($x_compatibility_date !== null) {
            $headerParams['X-Compatibility-Date'] = $x_compatibility_date->format('Y-m-d');
        }
        // header params
        if ($x_tenant !== null) {
            $headerParams['X-Tenant'] = ObjectSerializer::toHeaderValue($x_tenant);
        }

        // path params
        if ($attribute_id !== null) {
            $resourcePath = str_replace(
                '{' . 'attribute_id' . '}',
                ObjectSerializer::toPathValue($attribute_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDogmaDynamicItemsTypeIdItemId
     *
     * Get dynamic item information
     *
     * @param  int $item_id item_id (required)
     * @param  int $type_id type_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaDynamicItemsTypeIdItemId'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Tkhamez\Eve\API\Model\DogmaDynamicItemsTypeIdItemIdGet|\Tkhamez\Eve\API\Model\Error
     */
    public function getDogmaDynamicItemsTypeIdItemId($item_id, $type_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaDynamicItemsTypeIdItemId'][0])
    {
        list($response) = $this->getDogmaDynamicItemsTypeIdItemIdWithHttpInfo($item_id, $type_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);
        return $response;
    }

    /**
     * Operation getDogmaDynamicItemsTypeIdItemIdWithHttpInfo
     *
     * Get dynamic item information
     *
     * @param  int $item_id (required)
     * @param  int $type_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaDynamicItemsTypeIdItemId'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Tkhamez\Eve\API\Model\DogmaDynamicItemsTypeIdItemIdGet|\Tkhamez\Eve\API\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDogmaDynamicItemsTypeIdItemIdWithHttpInfo($item_id, $type_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaDynamicItemsTypeIdItemId'][0])
    {
        $request = $this->getDogmaDynamicItemsTypeIdItemIdRequest($item_id, $type_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\DogmaDynamicItemsTypeIdItemIdGet',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Tkhamez\Eve\API\Model\DogmaDynamicItemsTypeIdItemIdGet',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\DogmaDynamicItemsTypeIdItemIdGet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDogmaDynamicItemsTypeIdItemIdAsync
     *
     * Get dynamic item information
     *
     * @param  int $item_id (required)
     * @param  int $type_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaDynamicItemsTypeIdItemId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaDynamicItemsTypeIdItemIdAsync($item_id, $type_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaDynamicItemsTypeIdItemId'][0])
    {
        return $this->getDogmaDynamicItemsTypeIdItemIdAsyncWithHttpInfo($item_id, $type_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDogmaDynamicItemsTypeIdItemIdAsyncWithHttpInfo
     *
     * Get dynamic item information
     *
     * @param  int $item_id (required)
     * @param  int $type_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaDynamicItemsTypeIdItemId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaDynamicItemsTypeIdItemIdAsyncWithHttpInfo($item_id, $type_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaDynamicItemsTypeIdItemId'][0])
    {
        $returnType = '\Tkhamez\Eve\API\Model\DogmaDynamicItemsTypeIdItemIdGet';
        $request = $this->getDogmaDynamicItemsTypeIdItemIdRequest($item_id, $type_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDogmaDynamicItemsTypeIdItemId'
     *
     * @param  int $item_id (required)
     * @param  int $type_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaDynamicItemsTypeIdItemId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDogmaDynamicItemsTypeIdItemIdRequest($item_id, $type_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaDynamicItemsTypeIdItemId'][0])
    {

        // verify the required parameter 'item_id' is set
        if ($item_id === null || (is_array($item_id) && count($item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_id when calling getDogmaDynamicItemsTypeIdItemId'
            );
        }

        // verify the required parameter 'type_id' is set
        if ($type_id === null || (is_array($type_id) && count($type_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type_id when calling getDogmaDynamicItemsTypeIdItemId'
            );
        }

        // verify the required parameter 'x_compatibility_date' is set
        if ($x_compatibility_date === null || (is_array($x_compatibility_date) && count($x_compatibility_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_compatibility_date when calling getDogmaDynamicItemsTypeIdItemId'
            );
        }





        $resourcePath = '/dogma/dynamic/items/{type_id}/{item_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($if_none_match !== null) {
            $headerParams['If-None-Match'] = ObjectSerializer::toHeaderValue($if_none_match);
        }
        // header params
        if ($x_compatibility_date !== null) {
            $headerParams['X-Compatibility-Date'] = $x_compatibility_date->format('Y-m-d');
        }
        // header params
        if ($x_tenant !== null) {
            $headerParams['X-Tenant'] = ObjectSerializer::toHeaderValue($x_tenant);
        }

        // path params
        if ($item_id !== null) {
            $resourcePath = str_replace(
                '{' . 'item_id' . '}',
                ObjectSerializer::toPathValue($item_id),
                $resourcePath
            );
        }
        // path params
        if ($type_id !== null) {
            $resourcePath = str_replace(
                '{' . 'type_id' . '}',
                ObjectSerializer::toPathValue($type_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDogmaEffects
     *
     * Get effects
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffects'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return int[]|\Tkhamez\Eve\API\Model\Error
     */
    public function getDogmaEffects($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffects'][0])
    {
        list($response) = $this->getDogmaEffectsWithHttpInfo($x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);
        return $response;
    }

    /**
     * Operation getDogmaEffectsWithHttpInfo
     *
     * Get effects
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffects'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of int[]|\Tkhamez\Eve\API\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDogmaEffectsWithHttpInfo($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffects'][0])
    {
        $request = $this->getDogmaEffectsRequest($x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'int[]',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'int[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'int[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDogmaEffectsAsync
     *
     * Get effects
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffects'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaEffectsAsync($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffects'][0])
    {
        return $this->getDogmaEffectsAsyncWithHttpInfo($x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDogmaEffectsAsyncWithHttpInfo
     *
     * Get effects
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffects'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaEffectsAsyncWithHttpInfo($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffects'][0])
    {
        $returnType = 'int[]';
        $request = $this->getDogmaEffectsRequest($x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDogmaEffects'
     *
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffects'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDogmaEffectsRequest($x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffects'][0])
    {

        // verify the required parameter 'x_compatibility_date' is set
        if ($x_compatibility_date === null || (is_array($x_compatibility_date) && count($x_compatibility_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_compatibility_date when calling getDogmaEffects'
            );
        }





        $resourcePath = '/dogma/effects';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($if_none_match !== null) {
            $headerParams['If-None-Match'] = ObjectSerializer::toHeaderValue($if_none_match);
        }
        // header params
        if ($x_compatibility_date !== null) {
            $headerParams['X-Compatibility-Date'] = $x_compatibility_date->format('Y-m-d');
        }
        // header params
        if ($x_tenant !== null) {
            $headerParams['X-Tenant'] = ObjectSerializer::toHeaderValue($x_tenant);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDogmaEffectsEffectId
     *
     * Get effect information
     *
     * @param  int $effect_id effect_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffectsEffectId'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Tkhamez\Eve\API\Model\DogmaEffectsEffectIdGet|\Tkhamez\Eve\API\Model\Error
     */
    public function getDogmaEffectsEffectId($effect_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffectsEffectId'][0])
    {
        list($response) = $this->getDogmaEffectsEffectIdWithHttpInfo($effect_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);
        return $response;
    }

    /**
     * Operation getDogmaEffectsEffectIdWithHttpInfo
     *
     * Get effect information
     *
     * @param  int $effect_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffectsEffectId'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Tkhamez\Eve\API\Model\DogmaEffectsEffectIdGet|\Tkhamez\Eve\API\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDogmaEffectsEffectIdWithHttpInfo($effect_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffectsEffectId'][0])
    {
        $request = $this->getDogmaEffectsEffectIdRequest($effect_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\DogmaEffectsEffectIdGet',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Tkhamez\Eve\API\Model\DogmaEffectsEffectIdGet',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\DogmaEffectsEffectIdGet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDogmaEffectsEffectIdAsync
     *
     * Get effect information
     *
     * @param  int $effect_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffectsEffectId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaEffectsEffectIdAsync($effect_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffectsEffectId'][0])
    {
        return $this->getDogmaEffectsEffectIdAsyncWithHttpInfo($effect_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDogmaEffectsEffectIdAsyncWithHttpInfo
     *
     * Get effect information
     *
     * @param  int $effect_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffectsEffectId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDogmaEffectsEffectIdAsyncWithHttpInfo($effect_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffectsEffectId'][0])
    {
        $returnType = '\Tkhamez\Eve\API\Model\DogmaEffectsEffectIdGet';
        $request = $this->getDogmaEffectsEffectIdRequest($effect_id, $x_compatibility_date, $accept_language, $if_none_match, $x_tenant, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDogmaEffectsEffectId'
     *
     * @param  int $effect_id (required)
     * @param  \DateTime $x_compatibility_date The compatibility date for the request. (required)
     * @param  string|null $accept_language The language to use for the response. Defaults to &#39;en&#39;. (optional)
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_tenant The tenant ID for the request. Defaults to &#39;tranquility&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDogmaEffectsEffectId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDogmaEffectsEffectIdRequest($effect_id, $x_compatibility_date, $accept_language = null, $if_none_match = null, $x_tenant = null, string $contentType = self::contentTypes['getDogmaEffectsEffectId'][0])
    {

        // verify the required parameter 'effect_id' is set
        if ($effect_id === null || (is_array($effect_id) && count($effect_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $effect_id when calling getDogmaEffectsEffectId'
            );
        }

        // verify the required parameter 'x_compatibility_date' is set
        if ($x_compatibility_date === null || (is_array($x_compatibility_date) && count($x_compatibility_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_compatibility_date when calling getDogmaEffectsEffectId'
            );
        }





        $resourcePath = '/dogma/effects/{effect_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($if_none_match !== null) {
            $headerParams['If-None-Match'] = ObjectSerializer::toHeaderValue($if_none_match);
        }
        // header params
        if ($x_compatibility_date !== null) {
            $headerParams['X-Compatibility-Date'] = $x_compatibility_date->format('Y-m-d');
        }
        // header params
        if ($x_tenant !== null) {
            $headerParams['X-Tenant'] = ObjectSerializer::toHeaderValue($x_tenant);
        }

        // path params
        if ($effect_id !== null) {
            $resourcePath = str_replace(
                '{' . 'effect_id' . '}',
                ObjectSerializer::toPathValue($effect_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
