<?php
/**
 * RoutesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Tkhamez\Eve\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Stable Infrastructure (ESI) - tranquility
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-11-06
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tkhamez\Eve\API\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Tkhamez\Eve\API\ApiException;
use Tkhamez\Eve\API\Configuration;
use Tkhamez\Eve\API\FormDataProcessor;
use Tkhamez\Eve\API\HeaderSelector;
use Tkhamez\Eve\API\ObjectSerializer;

/**
 * RoutesApi Class Doc Comment
 *
 * @category Class
 * @package  Tkhamez\Eve\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RoutesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'postRoute' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation postRoute
     *
     * Get route between two systems
     *
     * @param  int $origin_system_id Origin system (required)
     * @param  int $destination_system_id Destination system (required)
     * @param  \Tkhamez\Eve\API\Model\RouteRequestBody $route_request_body route_request_body (required)
     * @param  string|null $accept_language The language to use for the response. (optional, default to 'en')
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_compatibility_date The compatibility date for the request. (optional, default to '2025-11-06')
     * @param  string|null $x_tenant The tenant ID for the request. (optional, default to 'tranquility')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postRoute'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Tkhamez\Eve\API\Model\Route|\Tkhamez\Eve\API\Model\Error
     */
    public function postRoute($origin_system_id, $destination_system_id, $route_request_body, $accept_language = 'en', $if_none_match = null, $x_compatibility_date = '2025-11-06', $x_tenant = 'tranquility', string $contentType = self::contentTypes['postRoute'][0])
    {
        list($response) = $this->postRouteWithHttpInfo($origin_system_id, $destination_system_id, $route_request_body, $accept_language, $if_none_match, $x_compatibility_date, $x_tenant, $contentType);
        return $response;
    }

    /**
     * Operation postRouteWithHttpInfo
     *
     * Get route between two systems
     *
     * @param  int $origin_system_id Origin system (required)
     * @param  int $destination_system_id Destination system (required)
     * @param  \Tkhamez\Eve\API\Model\RouteRequestBody $route_request_body (required)
     * @param  string|null $accept_language The language to use for the response. (optional, default to 'en')
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_compatibility_date The compatibility date for the request. (optional, default to '2025-11-06')
     * @param  string|null $x_tenant The tenant ID for the request. (optional, default to 'tranquility')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postRoute'] to see the possible values for this operation
     *
     * @throws \Tkhamez\Eve\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Tkhamez\Eve\API\Model\Route|\Tkhamez\Eve\API\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function postRouteWithHttpInfo($origin_system_id, $destination_system_id, $route_request_body, $accept_language = 'en', $if_none_match = null, $x_compatibility_date = '2025-11-06', $x_tenant = 'tranquility', string $contentType = self::contentTypes['postRoute'][0])
    {
        $request = $this->postRouteRequest($origin_system_id, $destination_system_id, $route_request_body, $accept_language, $if_none_match, $x_compatibility_date, $x_tenant, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\Route',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Tkhamez\Eve\API\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Tkhamez\Eve\API\Model\Route',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\Route',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Tkhamez\Eve\API\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postRouteAsync
     *
     * Get route between two systems
     *
     * @param  int $origin_system_id Origin system (required)
     * @param  int $destination_system_id Destination system (required)
     * @param  \Tkhamez\Eve\API\Model\RouteRequestBody $route_request_body (required)
     * @param  string|null $accept_language The language to use for the response. (optional, default to 'en')
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_compatibility_date The compatibility date for the request. (optional, default to '2025-11-06')
     * @param  string|null $x_tenant The tenant ID for the request. (optional, default to 'tranquility')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postRoute'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postRouteAsync($origin_system_id, $destination_system_id, $route_request_body, $accept_language = 'en', $if_none_match = null, $x_compatibility_date = '2025-11-06', $x_tenant = 'tranquility', string $contentType = self::contentTypes['postRoute'][0])
    {
        return $this->postRouteAsyncWithHttpInfo($origin_system_id, $destination_system_id, $route_request_body, $accept_language, $if_none_match, $x_compatibility_date, $x_tenant, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postRouteAsyncWithHttpInfo
     *
     * Get route between two systems
     *
     * @param  int $origin_system_id Origin system (required)
     * @param  int $destination_system_id Destination system (required)
     * @param  \Tkhamez\Eve\API\Model\RouteRequestBody $route_request_body (required)
     * @param  string|null $accept_language The language to use for the response. (optional, default to 'en')
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_compatibility_date The compatibility date for the request. (optional, default to '2025-11-06')
     * @param  string|null $x_tenant The tenant ID for the request. (optional, default to 'tranquility')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postRoute'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postRouteAsyncWithHttpInfo($origin_system_id, $destination_system_id, $route_request_body, $accept_language = 'en', $if_none_match = null, $x_compatibility_date = '2025-11-06', $x_tenant = 'tranquility', string $contentType = self::contentTypes['postRoute'][0])
    {
        $returnType = '\Tkhamez\Eve\API\Model\Route';
        $request = $this->postRouteRequest($origin_system_id, $destination_system_id, $route_request_body, $accept_language, $if_none_match, $x_compatibility_date, $x_tenant, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postRoute'
     *
     * @param  int $origin_system_id Origin system (required)
     * @param  int $destination_system_id Destination system (required)
     * @param  \Tkhamez\Eve\API\Model\RouteRequestBody $route_request_body (required)
     * @param  string|null $accept_language The language to use for the response. (optional, default to 'en')
     * @param  string|null $if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag. (optional)
     * @param  string|null $x_compatibility_date The compatibility date for the request. (optional, default to '2025-11-06')
     * @param  string|null $x_tenant The tenant ID for the request. (optional, default to 'tranquility')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postRoute'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postRouteRequest($origin_system_id, $destination_system_id, $route_request_body, $accept_language = 'en', $if_none_match = null, $x_compatibility_date = '2025-11-06', $x_tenant = 'tranquility', string $contentType = self::contentTypes['postRoute'][0])
    {

        // verify the required parameter 'origin_system_id' is set
        if ($origin_system_id === null || (is_array($origin_system_id) && count($origin_system_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $origin_system_id when calling postRoute'
            );
        }

        // verify the required parameter 'destination_system_id' is set
        if ($destination_system_id === null || (is_array($destination_system_id) && count($destination_system_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $destination_system_id when calling postRoute'
            );
        }

        // verify the required parameter 'route_request_body' is set
        if ($route_request_body === null || (is_array($route_request_body) && count($route_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $route_request_body when calling postRoute'
            );
        }






        $resourcePath = '/route/{origin_system_id}/{destination_system_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }
        // header params
        if ($if_none_match !== null) {
            $headerParams['If-None-Match'] = ObjectSerializer::toHeaderValue($if_none_match);
        }
        // header params
        if ($x_compatibility_date !== null) {
            $headerParams['X-Compatibility-Date'] = ObjectSerializer::toHeaderValue($x_compatibility_date);
        }
        // header params
        if ($x_tenant !== null) {
            $headerParams['X-Tenant'] = ObjectSerializer::toHeaderValue($x_tenant);
        }

        // path params
        if ($origin_system_id !== null) {
            $resourcePath = str_replace(
                '{' . 'origin_system_id' . '}',
                ObjectSerializer::toPathValue($origin_system_id),
                $resourcePath
            );
        }
        // path params
        if ($destination_system_id !== null) {
            $resourcePath = str_replace(
                '{' . 'destination_system_id' . '}',
                ObjectSerializer::toPathValue($destination_system_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($route_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($route_request_body));
            } else {
                $httpBody = $route_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
