<?php
/**
 * CorporationsProjectsDetailContribution
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tkhamez\Eve\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Stable Infrastructure (ESI) - tranquility
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-30
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tkhamez\Eve\API\Model;

use \ArrayAccess;
use \Tkhamez\Eve\API\ObjectSerializer;

/**
 * CorporationsProjectsDetailContribution Class Doc Comment
 *
 * @category Class
 * @package  Tkhamez\Eve\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CorporationsProjectsDetailContribution implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CorporationsProjectsDetailContribution';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'participation_limit' => 'int',
        'reward_per_contribution' => 'float',
        'submission_limit' => 'int',
        'submission_multiplier' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'participation_limit' => 'int64',
        'reward_per_contribution' => 'double',
        'submission_limit' => 'int64',
        'submission_multiplier' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'participation_limit' => false,
        'reward_per_contribution' => false,
        'submission_limit' => false,
        'submission_multiplier' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'participation_limit' => 'participation_limit',
        'reward_per_contribution' => 'reward_per_contribution',
        'submission_limit' => 'submission_limit',
        'submission_multiplier' => 'submission_multiplier'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'participation_limit' => 'setParticipationLimit',
        'reward_per_contribution' => 'setRewardPerContribution',
        'submission_limit' => 'setSubmissionLimit',
        'submission_multiplier' => 'setSubmissionMultiplier'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'participation_limit' => 'getParticipationLimit',
        'reward_per_contribution' => 'getRewardPerContribution',
        'submission_limit' => 'getSubmissionLimit',
        'submission_multiplier' => 'getSubmissionMultiplier'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('participation_limit', $data ?? [], null);
        $this->setIfExists('reward_per_contribution', $data ?? [], null);
        $this->setIfExists('submission_limit', $data ?? [], null);
        $this->setIfExists('submission_multiplier', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets participation_limit
     *
     * @return int|null
     */
    public function getParticipationLimit()
    {
        return $this->container['participation_limit'];
    }

    /**
     * Sets participation_limit
     *
     * @param int|null $participation_limit Limit on the contribution of the individual participant
     *
     * @return self
     */
    public function setParticipationLimit($participation_limit)
    {
        if (is_null($participation_limit)) {
            throw new \InvalidArgumentException('non-nullable participation_limit cannot be null');
        }
        $this->container['participation_limit'] = $participation_limit;

        return $this;
    }

    /**
     * Gets reward_per_contribution
     *
     * @return float|null
     */
    public function getRewardPerContribution()
    {
        return $this->container['reward_per_contribution'];
    }

    /**
     * Sets reward_per_contribution
     *
     * @param float|null $reward_per_contribution ISK reward per contribution
     *
     * @return self
     */
    public function setRewardPerContribution($reward_per_contribution)
    {
        if (is_null($reward_per_contribution)) {
            throw new \InvalidArgumentException('non-nullable reward_per_contribution cannot be null');
        }
        $this->container['reward_per_contribution'] = $reward_per_contribution;

        return $this;
    }

    /**
     * Gets submission_limit
     *
     * @return int|null
     */
    public function getSubmissionLimit()
    {
        return $this->container['submission_limit'];
    }

    /**
     * Sets submission_limit
     *
     * @param int|null $submission_limit Limit on amount of contribution per submission
     *
     * @return self
     */
    public function setSubmissionLimit($submission_limit)
    {
        if (is_null($submission_limit)) {
            throw new \InvalidArgumentException('non-nullable submission_limit cannot be null');
        }
        $this->container['submission_limit'] = $submission_limit;

        return $this;
    }

    /**
     * Gets submission_multiplier
     *
     * @return float|null
     */
    public function getSubmissionMultiplier()
    {
        return $this->container['submission_multiplier'];
    }

    /**
     * Sets submission_multiplier
     *
     * @param float|null $submission_multiplier Multiplier towards progress per contribution
     *
     * @return self
     */
    public function setSubmissionMultiplier($submission_multiplier)
    {
        if (is_null($submission_multiplier)) {
            throw new \InvalidArgumentException('non-nullable submission_multiplier cannot be null');
        }
        $this->container['submission_multiplier'] = $submission_multiplier;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


